CREATE SEQUENCE IF NOT EXISTS SEQ_ID_CLIENT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_ID_VEHICLE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_ID_SIZE
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS SEQ_ID_COLOR
START WITH 1
INCREMENT BY 1;


CREATE TABLE CLIENT (
      ID_CLIENT BIGINT DEFAULT SEQ_ID_CLIENT.NEXTVAL,
      NAME VARCHAR(80) NOT NULL,
      TELEPHONE VARCHAR(12) NOT NULL,
      DOCUMENT VARCHAR(15) NOT NULL,
      PRIMARY KEY (ID_CLIENT)
);
CREATE TABLE COLOR (
      ID_COLOR BIGINT DEFAULT SEQ_ID_COLOR.NEXTVAL,
      DESCRIPTION VARCHAR(20) NOT NULL,
      PRIMARY KEY (ID_COLOR)
);
CREATE TABLE SIZE (
      ID_SIZE BIGINT DEFAULT SEQ_ID_SIZE.NEXTVAL,
      DESCRIPTION VARCHAR(20) NOT NULL,
      PRIMARY KEY (ID_SIZE)
);
CREATE TABLE VEHICLE (
      ID_VEHICLE BIGINT DEFAULT SEQ_ID_VEHICLE.NEXTVAL,
      PLATE VARCHAR(9) NOT NULL,
      MODEL VARCHAR(50) NOT NULL,
      ID_SIZE INTEGER NOT NULL, -- 1 - Pequeno, 2 - Medio, 3 Grande
      ID_COLOR INTEGER NOT NULL,
      ID_CLIENT BIGINT NOT NULL,
      PRIMARY KEY (ID_VEHICLE),
      FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
      FOREIGN KEY (ID_COLOR) REFERENCES COLOR(ID_COLOR),
      FOREIGN KEY (ID_SIZE) REFERENCES SIZE(ID_SIZE)
);

INSERT INTO VEHICLE (ID_VEHICLE, PLATE, MODEL, ID_SIZE, ID_COLOR, ID_CLIENT) VALUES (SEQ_ID_VEHICLE.nextval,'URL 1234','BMW',1,5,2);
INSERT INTO VEHICLE (ID_VEHICLE, PLATE, MODEL, ID_SIZE, ID_COLOR, ID_CLIENT) VALUES (SEQ_ID_VEHICLE.nextval,'URL 0987','Corolla',2,3,2);

INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (1, 'Preto') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (2, 'Prata') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (3, 'Branco') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (4, 'Amarelo') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (5, 'Vermelho');
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (6, 'Azul') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (7, 'Verde') ;
INSERT INTO COLOR(ID_COLOR,DESCRIPTION) VALUES (8, 'Outro') ;

INSERT INTO SIZE(ID_SIZE,DESCRIPTION) VALUES (1, 'Pequeno') ;
INSERT INTO SIZE(ID_SIZE,DESCRIPTION) VALUES (2, 'Medio') ;
INSERT INTO SIZE(ID_SIZE,DESCRIPTION) VALUES (3, 'Grande');